### ISSUE TITLE
search engine visibility

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#102]
Will hid oregonconservationstrategy.org from google search engine while until it is up and running. Need to figure out how to make it visible again to search engines before we hand over the site.

**Comment by alisonjbates** [comment]
This is all set. We can’t guarantee when Google will index the site, but this removes the on-site request for Google to ignore the website.

Settings-> Reading-> uncheck "Discourage search engines from indexing this site"

**Comment by dnseminara** [comment]
Hah. I was JUST about to comment as well @alisonjbates.

I think the splash page plugin is also a contributer.

![screen shot 2016-08-22 at 10 09 38 am](https://cloud.githubusercontent.com/assets/6739893/17863906/9f5bbefa-6850-11e6-82b4-34725a99c246.png)

I also couldn't find any robots.txt on the server - so we may just have to wait until we deactivate the plugin

**Comment by alisonjbates** [comment]
Absolutely.

**Comment by ldford** [comment]
Great. Thanks, both. Looks like they will deactivate the splash page plugin on Sept. 2.

**Comment by ldford** [comment]
@dnseminara Site is live. Can we do the Google Search Console thing?

**Comment by dnseminara** [comment]
@ldford - i beat ya to it...knowing it would take awhile.  **Plugins** -> **XML Site Map**

![screen shot 2016-09-01 at 3 50 50 pm](https://cloud.githubusercontent.com/assets/6739893/18187129/e1be51c8-705b-11e6-83fe-3d0b65f752cc.png)

**Comment by ldford** [comment]
thank you!
