### ISSUE TITLE
TESTING: Confirm that Dev is mostly functional before developing features

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ocs-wp#106]
* [x] Ecoregions
   * [x]  SVG Map
      * click on an ecoregion to open an Ecoregion Page
      * [x]  Specific Ecoregion Page Map opens Compass
* [x] Main Page
* [x] Search
* [x] Information Icon
   * [x] Tooltips in main text work
* [x] Clicking "Conserve" in top right takes you to homepage
* [x] Overview
* [x] Key Conservation Issues
   * [x] Tile View
   * [x] List View
* [x] COAs
   * [x] Loads Compass in view
   * [x] Legend Works
   * [x] "View Data Layers In Compass" takes you to Compass
* [x] Strategy Habitats
* [x] Strategy Species
* [x] Monitoring
* [x] Conservation Toolbox
* [x] Oregon Nearshore Strategy
* [x] Footer link for ODFW OCS page
* [x] Info icon expands/closes on images
* [x] Right nav is sticky and updates with scrollbar

**Comment by pollardld** [comment]
SVG map not working. looks like jquery version is no longer supported/hosted on google APIs. Once this is fixed, will test again.

**Comment by pollardld** [comment]
Needed svg image in place to function correctly. 

My first attempt to transfer media files from server to local did not complete. 
My second attempt did complete and resolve this problem.
