### ISSUE TITLE
Sticky Left Nav

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ocs-wp#107]
* [x] Items in left navigation scroll independently from main content panel.
* [x] Items in left navigation do not have a scrollbar if they all fit on screen

**Comment by pollardld** [comment]
one calculation throwing this off. almost done though.

**Comment by pollardld** [comment]
f

**Comment by pollardld** [comment]
Page used for testing: /ecoregion/east-cascades/

Tests:
  - items in left nav scroll independently from main content panel
  - items in left nav do not have a scrollbar if they all fit on screen

Browsers Tested:  
  - [x] FF 66; Windows 10
  - [x] Chrome 75; Windows 10
  - [x] IE 11; Windows 10
  - [x] Edge 18; Windows 10
  - [x] IE 11; Windows 8.1
  - [x] IE 10; Windows 8
  - [x] Chrome 76; Mac OS X
  - [x] Safari 12.1.1; Mac OS X
  - [x] FF 68; Mac OS X


<img width="1680" alt="Screen Shot 2019-05-24 at 4 05 13 PM" src="https://user-images.githubusercontent.com/2632164/58360463-d00b0a00-7e3d-11e9-9f4e-53e8aae6d70e.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 04 16 PM" src="https://user-images.githubusercontent.com/2632164/58360467-d600eb00-7e3d-11e9-9247-1b1f181a4d48.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 05 24 PM" src="https://user-images.githubusercontent.com/2632164/58360458-cbdeec80-7e3d-11e9-8be5-a8e16ee4db11.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 04 07 PM" src="https://user-images.githubusercontent.com/2632164/58360471-da2d0880-7e3d-11e9-9ae5-9ce9da4a882b.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 04 16 PM" src="https://user-images.githubusercontent.com/2632164/58360472-dac59f00-7e3d-11e9-890e-dcdbbb0e7985.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 03 35 PM" src="https://user-images.githubusercontent.com/2632164/58360476-def1bc80-7e3d-11e9-9cbc-54e1a1f39c35.png">

<img width="1680" alt="Screen Shot 2019-05-24 at 4 02 56 PM" src="https://user-images.githubusercontent.com/2632164/58360482-e3b67080-7e3d-11e9-83f9-c257066b1d64.png">
