### ISSUE TITLE
Identify WP Plugin for .PDF export

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ocs-wp#117]
Plugin should:
* [x] Work on most major browsers
   * [x] Chrome
   * [x] FireFox
   * [x] Safari
   * [x] Edge
   * [x] IE 11? (review Analytics)
* [x] Attach Cover Sheet
* [x] Able to target div for export (doesn't just print page)
* [x] (Optional) Can export multiple sections
   * [ ] OMVP Hard Code
   * [x] Bonus Points: WP Admin controlled
   * [ ] Gold Star: User identified

* [ ] (Bad case) Javascript/jQuery/etc... tool
* [ ] (Worst Case) Identify strategy to write by hand

**Comment by pollardld** [comment]
[Found a promising option](https://wordpress.org/plugins/kalins-pdf-creation-station/).  

Here is a basic prototype while i work on one to share with ODFW.  

[ecoregions.pdf](https://github.com/Ecotrust/ocs-wp/files/3238520/ecoregions.pdf)

**Comment by pollardld** [comment]
Prototype at #118
