### ISSUE TITLE
.PDF Export Prototype ready for ODFW Review

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ocs-wp#118]
Have an example of PDF export for ODFW to use as shared language to tell us what they ACTUALLY want (in detail).

**Comment by pollardld** [comment]
<details>
<summary>Details</summary>

## Areas of current PDFs, [example](http://oregonconservationstrategy.org/media/3-Ecoregions-4.12.17.pdf), that will not be replicable in generated PDFs  

### Content within a single text area  
When content differs (pdf vs web) within a single text area. For example:  

**Ecoregions** - PDF version has map included between what falls within a single text area in web version

|  PDF  |  Web  |
|-------|-------|
| <img width="500" alt="Screen Shot 2019-06-05 at 5 21 19 PM" src="https://user-images.githubusercontent.com/2632164/58998821-9def9580-87b7-11e9-8471-e8a82c89a431.png"> | <img width="500" alt="Screen Shot 2019-06-05 at 5 36 30 PM" src="https://user-images.githubusercontent.com/2632164/58999005-7c42de00-87b8-11e9-94c6-bfbe4c889bae.png"> |

----  





</details>

**Comment by pollardld** [comment]
Ready for review: [ecoregions.pdf](https://github.com/Ecotrust/ocs-wp/files/3270121/ecoregions.pdf)

**Comment by pollardld** [comment]
### Review Feedback  

Todo:  

- [ ] Character set (encoding): the apostrophe character being used is not being interpreted correctly:
For example: page 3 -
"Oregon Conservation Strategy ecoregionsÂ provide information on each of Oregonâ€™s nine ecoregions..."
I suspect much of the text content was written in a Word doc then copied into WordPress, preserving Microsoft's stylized special characters
See if you can't set the .PDF export to use Unicode or at least a set with more characters like Latin-1 to see if that fixes some issues
If not, see if you can't insert a pre-processor to detect the most common special characters and replace them with appropriate ASCII versions.
- [ ] Photo Caption markup: there's some lingering markup text that gets printed around photos and their captions
  for example on pages 6-7 around photo of Middle Fork of John Day
[caption id="attachment_5583" align="alignnone" width="492"] ... [/caption]
- [ ] Random numbers: 
  Every few pages there's a random number sitting by itself
  For example: Page 12, under "Limiting Factors And Approaches", the number "2544" shows up.
  Do we know where this is coming from and/or why this is happening?
