### ISSUE TITLE
Make design recommendations

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ocs-wp#123]
Recommendations for:

- [x] style of icons in top nav when open/closing map, grid, and list
  - [x] make consistant across pages
    - different implementations throughout the site
  - [x] closing the map icon style and positioning
  - [x] style change on active icon
  <img width="255" alt="Screen Shot 2019-06-17 at 3 10 53 PM" src="https://user-images.githubusercontent.com/2632164/59640274-661b1300-9112-11e9-9b99-12fd8bcc1d18.png">

---  

- [x] download links/buttons for each post pdf section
  - *e.g.*, button to download Blue Mountains post
  - *e.g.*, all ecoregion packet download

**Comment by pollardld** [comment]
Suggestion for top nav icons:
  - add new icon for article 
  - new styles active icon 
  - leave grid, list and map icons for pages such as [Ecoregions](http://oregonconservationstrategy.org/ecoregions/)
  - for pages such as a [Single Ecoregion](http://oregonconservationstrategy.org/ecoregion/blue-mountains/) show icons for map and article, with article icon defaulted to active
    <img width="266" alt="Screen Shot 2019-06-20 at 11 46 33 AM" src="https://user-images.githubusercontent.com/2632164/59873695-68b77b80-9351-11e9-9ae8-b9106a8cbca1.png">

**Comment by ldford** [comment]
Noted. I like it. I'll share with ODFW and get their thoughts.
