### ISSUE TITLE
Import COA CSV files

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#14]
Conservation Opportunity Areas will come as a single *very* long excel doc with multiple rows per COA

Example table below for one COA. Couple of notes:  
* Anything a number in the `WordpressID` column is meant to linked to an existing WP content item. 
* Species associations also have a 'status' associated with them (`Modeled Habitat` or `Observed`) and this needs to be a) expressed in the admin so that it can be edited over time and b) output with each species association on the template side
* Many fields in column B ("Category") will have more than one row associated with it. For instance 
"Local Conservation Actions and Plans". With CMB2, these need to be repeater fields (fieldsets) so that they can be edited/expanded/contracted within the admin by editors.
* The `COAID` is separate from the WordPress post ID and needs to be maintained as it relates to external data.
* Columns `TGTID` and `MainER` can be ignored.

https://wordpress.org/plugins/really-simple-csv-importer/ is currently installed and supports updating. There are hooks to transform imported data before it hits the DB (as well as a way to do test imports). Some CSV transformations are already in place here in the site plugin https://github.com/Ecotrust/ocs-wp/blob/master/app/plugins/ocs-site-customizations/odfw-customizations.php#L67 

| COAName          | COAID | Category                             | SubCategory                         | Item                                                                                                                                                   | Link                                                                                       | SpeciesType     | DataSource                                      | WordpressID |
|------------------|-------|--------------------------------------|-------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|-----------------|-------------------------------------------------|-------------|
| Summer Lake Area | 189   | COA Description                      |                                     | This area is comprised of Summer Lake and the surrounding high desert wetlands subregion, including much of the Diablo Mountain Wilderness Study Area. |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Ecoregion                            |                                     | East Cascades                                                                                                                                          |                                                                                            |                 | Oregon Conservation Strategy Ecoregions, 2015   | 60          |
| Summer Lake Area | 189   | Ecoregion                            |                                     | Northern Basin and Range                                                                                                                               |                                                                                            |                 | Oregon Conservation Strategy Ecoregions, 2015   | 62          |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Important Bird Areas of Oregon                                                                                                                         | http://netapp.audubon.org/IBA/State/US-OR                                                  |                 | Oregon Conservation Strategy COA Analysis, 2015 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Intermountain West Joint Venture Implementation Plan (2013)                                                                                            | http://iwjv.org/2013-implementation-plan                                                   |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Intermountain West Waterbird Conservation Plan (Ivey and Herziger 2006)                                                                                | http://www.fws.gov/pacific/migratorybirds/PDF/IWWCP.pdf                                    |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Coordinated Implementation Plan for Bird Conservation in Eastern Oregon (Taylor et.al. 2005)                                                           | http://iwjv.org/sites/default/files/easternoregoncip.pdf                                   |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | East-side All-Bird Implementation Plan (Ivey 2000)                                                                                                     |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Interior Columbia Basin Strategy (developed 2003, revised 2014)                                                                                        | http://www.icbemp.gov/html/ICBEMP_Frameworkmemorandum-and-strategy_2014.pdf                |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Oregon Biodiversity Project Conservation Opportunity Areas                                                                                             |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Local Conservation Actions and Plans |                                     | Partners in Flight Columbia Plateau Conservation Strategy (Altman and Holmes 2000)                                                                     | http://www.orwapif.org/sites/default/files/columbia_basin.pdf                              |                 |                                                 |             |
| Summer Lake Area | 189   | Potential Partners                   |                                     | Ducks Unlimited                                                                                                                                        | http://www.ducks.org/                                                                      |                 |                                                 |             |
| Summer Lake Area | 189   | Potential Partners                   |                                     | USDA Natural Resources Conservation Service                                                                                                            | http://www.nrcs.usda.gov/wps/portal/nrcs/detail/or/contact/local/?cid=nrcs142p2_046129     |                 |                                                 |             |
| Summer Lake Area | 189   | Potential Partners                   |                                     | Oregon Hunters Association                                                                                                                             | http://www.oregonhunters.org/                                                              |                 |                                                 |             |
| Summer Lake Area | 189   | Potential Partners                   |                                     | The Oregon Watershed Enhancement Board                                                                                                                 | http://www.oregon.gov/oweb/Pages/index.aspx                                                |                 |                                                 |             |
| Summer Lake Area | 189   | Potential Partners                   |                                     | Lake County Soil and Water District                                                                                                                    | http://www.oregon.gov/ODA/shared/Documents/Publications/NaturalResources/SWCDDirectory.pdf |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Improve water delivery system within the Summer Lake area to improve effectiveness of wetland management.                                              |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Maintain diverse wetland habitats.                                                                                                                     |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Restore and maintain complex, continuous sage habitat.                                                                                                 |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Remove and control juniper encroachment into sage habitat.                                                                                             |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Promote early detection and suppression of invasive weeds.                                                                                             |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Recommended Conservation Actions     |                                     | Manage livestock grazing to promote healthy wetlands and riparian areas.                                                                               |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     | 2006 COA                            | 2006 COA ID NBR-02 (Summer Lake area)                                                                                                                  |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     | Protected Area                      | Diablo Mountain Wilderness Study Area                                                                                                                  |                                                                                            |                 | USGS Protected Areas Database, 2015             |             |
| Summer Lake Area | 189   | Special Features                     | Protected Area                      | Fremont-Winema National Forest                                                                                                                         |                                                                                            |                 | USGS Protected Areas Database, 2015             |             |
| Summer Lake Area | 189   | Special Features                     | Protected Area                      | Summer Lake Migratory Waterfowl And Game Management Area                                                                                               |                                                                                            |                 | USGS Protected Areas Database, 2015             |             |
| Summer Lake Area | 189   | Special Features                     | Protected Area                      | Summer Lake Wildlife Area                                                                                                                              |                                                                                            |                 | USGS Protected Areas Database, 2015             |             |
| Summer Lake Area | 189   | Special Features                     |                                     | KCI: Barriers to Fish and Wildlife Movement                                                                                                            |                                                                                            |                 |                                                 | 70          |
| Summer Lake Area | 189   | Special Features                     | Number of observed Strategy Species | 23                                                                                                                                                     |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     | Number of Strategy Habitats         | 6                                                                                                                                                      |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     |                                     | Diverse and expansive wetland complex (including playas, seasonal wetlands, etc.)                                                                      |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     |                                     | Important stop-over for migratory birds                                                                                                                |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Special Features                     |                                     | Includes ODFW Sage-Grouse Core Area                                                                                                                    |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Specialized Local Habitats           |                                     |                                                                                                                                                        |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Specialized Local Habitats           |                                     | Alkali Grasslands                                                                                                                                      |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Specialized Local Habitats           |                                     | Rock Habitats                                                                                                                                          |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Specialized Local Habitats           |                                     | Salt Desert Scrub                                                                                                                                      |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Specialized Local Habitats           |                                     | Springs                                                                                                                                                |                                                                                            |                 |                                                 |             |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Aspen Woodlands                                                                                                                                        |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 73          |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Flowing Water and Riparian                                                                                                                             |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 81          |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Natural Lakes                                                                                                                                          |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 78          |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Ponderosa Pine Woodlands                                                                                                                               |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 80          |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Sagebrush                                                                                                                                              |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 82          |
| Summer Lake Area | 189   | Strategy Habitat                     |                                     | Wetland                                                                                                                                                |                                                                                            |                 | Oregon Conservation Strategy COA Analysis, 2015 | 83          |
| Summer Lake Area | 189   | Strategy Species                     | Amphibian                           | Western Toad                                                                                                                                           |                                                                                            | Modeled Habitat | Oregon Conservation Strategy COA Analysis, 2015 | 1016        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | American White Pelican                                                                                                                                 |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1025        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Black-backed Woodpecker                                                                                                                                |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1029        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Black-necked Stilt                                                                                                                                     |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1030        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Caspian Tern                                                                                                                                           |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1034        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Ferruginous Hawk                                                                                                                                       |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1039        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Flammulated Owl                                                                                                                                        |                                                                                            | Modeled Habitat | Oregon Conservation Strategy COA Analysis, 2015 | 1040        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Franklin's Gull                                                                                                                                        |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1042        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Great Gray Owl                                                                                                                                         |                                                                                            | Modeled Habitat | Oregon Conservation Strategy COA Analysis, 2015 | 1044        |
| Summer Lake Area | 189   | Strategy Species                     | Bird                                | Greater Sage-grouse                                                                                                                                    |                                                                                            | Observed        | Oregon Conservation Strategy COA Analysis, 2015 | 1045        |

**Comment by ArtDezign** [comment]
Hey Will,

I'd like to go over all the mapping for this issue.  Specifically which columns would get mapped to which fields in the database.  That way I can setup the appropriate postypes and metadata.  I didn't get your email, so if you could email me, that would be great.

Thanks,

Lang

**Comment by willthemoor** [comment]
z.o.m.g. Closing!
