### ISSUE TITLE
Create In-Page Sidebar Jump Navigation

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#17]
Dynamic sidebar will be based on the headers within the page. Links simply jump to that header (ala Wikipedia). 

http://bryanbraun.github.io/anchorjs/ or similar should work well.

Should be on all single post templates for all content types including pages.

<img width="324" alt="screen shot 2015-09-07 at 12 38 10 am" src="https://cloud.githubusercontent.com/assets/54206/9711455/bec7f360-54f8-11e5-809a-1df0a8956162.png">

**Comment by ldford** [comment]
Also note that in-page sidebar remains fixed while scrolling.
![image](https://cloud.githubusercontent.com/assets/6453589/10496375/5e87a6a4-7275-11e5-949c-56eec9e3ea8f.png)

![image](https://cloud.githubusercontent.com/assets/6453589/10496378/6444bece-7275-11e5-947b-5ad4407070ed.png)

**Comment by willthemoor** [comment]
We'll also need to include sub page navigation in this area. After thinking about it, I don't think it needs to be manual at all—it's entirely tied to the page structure. `wp_list_pages` or something should be fine.

Basic Reqs: 

1. It will only be required for sections with nested page-based content (pretty much all sections of the OCS but not for the CPT views)
2. If possible, it shouldn't require authors to mess with it (based on page structure)
3. It should show siblings and immediate descendants but not sibling descendants (CSS hide is a-ok)
4. The current page parent's name should be output as a header above the sibling page nav
5. On page jump links should come be inserted after the page navigation with some sort of CSS separator between the two.
6. 100% positive it's not this cut and dried and will need to be tweaked for certain subsections and scenarios. :) 


If there is  a way to also include a manually created menu within this area. This

**Comment by willthemoor** [comment]
This is in place. Think we have more to talk about with regard to UX and design but I'm going to set this ticket to beta and remove high priority.
