### ISSUE TITLE
Add Photo Attribution/Caption UI

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#18]
Photos with attribution and/or a caption should have an (Info) icon added that reveals the photo information when clicked. Click again to hide.

<img width="362" alt="screen shot 2015-09-07 at 12 41 02 am" src="https://cloud.githubusercontent.com/assets/54206/9711530/25fc4eb4-54f9-11e5-9355-bdaabb026dbc.png">
<img width="347" alt="screen shot 2015-09-07 at 12 40 08 am" src="https://cloud.githubusercontent.com/assets/54206/9711531/25fcde6a-54f9-11e5-91f6-d5079559a1d6.png">

**Comment by dnseminara** [comment]
I've added the photo attribution feature for **single-strategy-species**. Are there any other post types that should have this functionality? I went through the admin, but could not see those URL meta fields elsewhere.

#### Initial View
On hover, the glyphicons increase in size to scream out a little more
![screen shot 2015-11-17 at 11 39 06 am](https://cloud.githubusercontent.com/assets/6739893/11222555/f7beb5f0-8d1f-11e5-8932-932a83a89703.png)


#### On click of *I*

![screen shot 2015-11-17 at 11 39 17 am](https://cloud.githubusercontent.com/assets/6739893/11222559/faf3ed58-8d1f-11e5-90dc-52122176fc0d.png)

**Comment by ldford** [comment]
This looks great, Drew, thanks. Single strategy species photos will be added via a spreadsheet upload with photo attribution included. All other pages (structured content plus just randomly throughout site) will have photos as well, that ODFW is uploading via the media gallery. They are adding photo attribution info there, and it will need to appear the same way once those photos are uploaded to pages.

**Comment by willthemoor** [comment]
There are attribution fields for Strategy Species only because all of those images will be hosted off site so it's the only way we could associate the attribution meta data with those remote URLs. 

For images that are uploaded directly to the admin within the OCS (everything else on the site), you can find the attribution fields in the Admin->Media Library->edit an image.

Here's some code you can stuff in a template to see what's coming out. Take these steps.

1. Edit a strategy habitat (any)
2. Click 'Set Featured Image' on the lower right
3. Either choose an image or upload one. Make sure all of the fields on the right are filled in for it. 
4. Save the post
5. Put this code into `/templates/content-single-strategy_habitat.php` anywhere

```php
	<pre>
	<?php
	// WP makes posts with the type "attachment" for media objects
	// name, description and caption are stored in the post object
	$att = get_post( get_post_thumbnail_id() );
	print_r($att);

	// Alt, attribution name and attribution url are stored as meta for that attachement post object
	$meta = get_post_meta( get_post_thumbnail_id() );
	print_r($meta);


	// output example
	$thumbnail = get_post( get_post_thumbnail_id() );
	echo $thumbnail->post_title . "<br>";
	echo $thumbnail->post_excerpt . "<br>";
	echo $thumbnail->post_content . "<br>";
	echo get_post_meta( $thumbnail->ID, '_wp_attachment_image_alt', true ) . "<br>";
	echo get_post_meta( $thumbnail->ID, 'odfw-attribution-name', true ) . "<br>";
	echo get_post_meta( $thumbnail->ID, 'odfw-attribution-url', true ) . "<br>";

	?>
	</pre>

	// Slightly more real world output example
	<figure>
	<?php
	//output the image
	the_post_thumbnail('large');
	$attrName = get_post_meta( get_post_thumbnail_id(), 'odfw-attribution-name', true );
	if ( !empty($attrName) ):
	?>
		<figcaption>
			<?php echo $attrName; ?>
		</figcaption>
	<?php endif; ?>
	</figure>

```

**Comment by dnseminara** [comment]
Nice! Thanks for spelling out the process. Are we only focusing on featured images? For example, it looks like [http://ocs.ecotrust.org/strategy-habitat/coastal-dunes/] (http://ocs.ecotrust.org/strategy-habitat/coastal-dunes/) does not currently have a featured image, but an image from the gallery that has been added to the first content field in the admin. It also looks like the attribution for the image is directly below - however somewhat seemingly unrelated or tied to the actual image itself.

I guess in several scenarios, people can have a 1) featured image, 2) just an attached image like coastal-dunes, or 3)a featured image and multiple attached images.

If so, would something similar to this looks work?

```javascript
   $args = array(
   	'post_type'   => 'attachment',
   	'numberposts' => -1,
   	'post_status' => 'any',
   	'post_parent' => $post->ID
   );

   $attachments = get_posts( $args );
```

**Comment by willthemoor** [comment]
Good catch. And yep re: the three possible scenarios.

1) All of the structured content pieces (ecoregions, strategy habitats...) other than COAs should have at least one featured image. This will be the big one we display at the top of the page as well as the one we use for the grid views. @ldford can you address this with the content team please?

2+3) I need to chew on this a bit. The code you have would certainly pull them out but would mean we'd need to parse `the_content` and replace inserted images. 

I'm wondering if for this project we should just use WordPress's default `[caption]` field to hold the attribution information. When an author inserts that into a post, by default, Wordpress will output the caption field within a `<figcaption>` element. Seems a lot easier. 

@ldford do you know how often, if at all, they'll be including a URL for the photographer? I think I may have just pulled this over from commonplace.  

PS, [responsive image support is going to land in WordPress core in v4.4](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) so we should be thinking about that.
