### ISSUE TITLE
Indicate Associated Content Counts in Main Menu

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#19]
When looking at a single template for any OCS custom post type (KCI, Ecoregion, COA, Strategy Habitat or Strategy Species) the site navigation should indicate the number of associations it has with other OCS custom post types.

Some associations are baked into each post's custom fields but some will need to be looked up. 

When the count icon is hovered it should reveal a list of (clickable) associated post titles.

<img width="361" alt="OCS main sidebar" src="https://cloud.githubusercontent.com/assets/54206/9711768/0f8b8030-54fb-11e5-8e10-93d41c1f3478.png">

<img width="409" alt="screen shot 2015-09-07 at 1 18 38 am" src="https://cloud.githubusercontent.com/assets/54206/9712637/d4a4d600-5500-11e5-8e81-ea61a73356ce.png">

**Comment by ldford** [comment]
@willthemoor - I would like to prioritize other items over this ticket. Fearing we won't have the budget to cover this one.

**Comment by willthemoor** [comment]
Agreed. Built a lot of this directly into the templates so I’m not so sure it's needed anyway. For instance, instead of a flat text list of Ecoregions, the templates have links (and sometimes photos) directly to the Ecoregions.

**Comment by ldford** [comment]
Associated content counts in main menu no longer needed since these associations among structured content items has been built into the templates.
