### ISSUE TITLE
Footer obscures iframe (and other?) content

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ocs-wp#24]
To replicate:
Scroll to the bottom of http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/ 

Notice that normal Compass bottom content is all obscured:
* zoom controls
* scale bar
* legend tab
* map attribution (which violates our use policy)

Unobstructed view can be seen here: http://52.25.124.64/visualize/#x=-121.65&y=44.11&z=7&logo=true&dls%5B%5D=true&dls%5B%5D=0.5&dls%5B%5D=456&basemap=ESRI+Ocean&themes%5Bids%5D%5B%5D=27&tab=data&print=true 

Making sure the page content has enough margin/padding to prevent content from spilling under the footer will be important.

**Comment by willthemoor** [comment]
This is all set.
