### ISSUE TITLE
<h> styling

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#26]
Noticing the < h2 > (Pulling Together to Make a Difference) is pretty small in comparison to < h3 > (A Solid Foundation). In the comps, I don't see examples of different levels of headers. Do you need me to request header styles from Josh (designer)?

**Comment by ldford** [comment]
Sorry - here is the example:

![image](https://cloud.githubusercontent.com/assets/6453589/10228634/a8c80a62-6828-11e5-93ad-15fedfaee3a1.png)

**Comment by ldford** [comment]
@selenastrain I am getting style guidelines from the designer for headers and tables. More soon.

**Comment by willthemoor** [comment]
@ldford I think we're good on this one. Can you double check? If so, please close this out.

**Comment by ldford** [comment]
@willthemoor I made this test page so we can look at headers: http://ocs.ecotrust.org/test-page/. These are the 5 changes I think we need to make:

1. H4 needs to come up in size one smidge. It's a little hard to read.
2. H5 - see Arty's directions: H5 should be exactly the same size as H4 only have NO padding between the header and the first line of copy below it. H4 DOES have padding. (possible?)
Screenshot:
![image](https://cloud.githubusercontent.com/assets/6453589/11699106/64dbcfd4-9e77-11e5-8f0b-d4ed2baaa0ef.png)

3. ODFW often uses a lot of copy in their headers. When that happens, the header copy is running to the right of text margins. Let's line that all up. Can we actually find a happy medium between the two? Extend the text margins a little more to the right, and reduce the Header margins - meet at the middle? (see dev screenshot)
4. Please increase the leading of ALL header sizes so that when they wrap, they will be more legible. (See comp versus dev)
5. Please increase the amount of padding BEFORE/above the header. (See comp versus dev)
Screenshot on RIGHT is of dev site long headers going too far to the right.
Screenshot on LEFT is of the comps that have increased leading in the headers.
![image](https://cloud.githubusercontent.com/assets/6453589/11699230/30531320-9e78-11e5-9241-afa29e48f322.png)

**Comment by willthemoor** [comment]
1. Complete
2. Compete
3. Not yet (need to do this when I do the other wrapping/right margin stuff)
4. Complete
5. Complete.

**Comment by ldford** [comment]
Looking great. Will review with Sarah Monday!
