### ISSUE TITLE
Sidebar Navigation - Structured Content Listings

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#38]
TBD: Should the sidebar on structured content pages (eg, ecoregions or strategy habitats) include a listing of the structured content items within the right sidebar?

For example, should the sidebar on http://ocs.ecotrust.org/strategy-habitats/ and it's subpages include a the list of Strategy Habitats?

At the moment, only Strategy Species includes this, sort of. It has a listing of all of top level species taxonomy items (Birds, Fish...).

**Comment by ldford** [comment]
In sidebar, list structured content for KCIs, Ecoregions, Strategy Habitats. For flyout menu, in cases of Strategy Habitats and Strategy Species, list structured content first followed by separate pages.
