### ISSUE TITLE
Hook Up Analytics

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#40]
Do they have an existing analytics package or should we just set up GA or similar for them?

**Comment by ldford** [comment]
I believe they have an existing analytics package. Let me reach out.

**Comment by ldford** [comment]
@willthemoor this is what Arty says. How do you recommend we move forward? We would need his password, I imagine?

ODFW has a Google Analytics account that my google account was added to so I could keep an eye on Compass usage. I think for the Strategy site it may be better for you to just set it up, and attach it to the newly created OregonConservationStrategy@gmail.com account I created when I bought the domain names. Then we can also look at transferring the Compass sites over as well, or figure that out with ODFW staff.

**Comment by willthemoor** [comment]
Asked AR to set this up on the GA side.

**Comment by willthemoor** [comment]
GA is hooked up and tracking.
