### ISSUE TITLE
Link Styles

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#41]
Links within body content are very hard to distinguish. See the third paragraph on http://ocs.ecotrust.org/conservation-opportunity-areas/. 

Let's add something like:
`
.main-content a {
    text-decoration: underline;
}
`
And perhaps a stronger hover.

**Comment by ldford** [comment]
Thank you. This was a question I asked Josh and never heard back on.

**Comment by willthemoor** [comment]
Incorrectly closed from a commit.
