### ISSUE TITLE
Icons - 2 updates

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#42]
These are the final, approved sidebar icons. I believe there are still a couple of updates, based on what I see here: https://github.com/Ecotrust/ocs-wp/commit/b9be482af3173a50f2c182975c5fd17e14fe91fc 

Overview - house (correct)
Statewide KCIs - key (correct)
Ecoregions - globe (correct)
COAs - 2 LEAVES (needs updating - currently as the tree in the code and the fish in dev)
Strategy Habitats - TREE (needs updating)
Strategy Species - bird head (correct)
Monitoring - eye (correct)
Conservation Toolbox - HAMMER (needs updating)
ONS - water droplet (correct)

**Comment by willthemoor** [comment]
OK! I took the ones that are up on dev from the [last PDF](https://asset1.basecamp.com/2491544/projects/8080337/attachments/188810028/8e1e8455ec63f1508e9a797bc13561d50010/original/OCS_101615B.pdf) Josh posted with the note "here's an updated pdf with the revised icons". :)

**Comment by ldford** [comment]
Yep! And above are the updates from the ODFW crew.
