### ISSUE TITLE
Style for map link "view data layers in compass"

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#43]
@willthemoor Drew needs icon or styling of some kind for what the comps show as:
![image](https://cloud.githubusercontent.com/assets/6453589/11159284/14f82940-8a13-11e5-943d-dc23e8dad168.png)

If you look in the indesign files, can you pull something out for him, and then reassign?

**Comment by willthemoor** [comment]
@dnseminara  The compass icon is now built into the main icon sprite. Somewhere around ` -62px -871px`
