### ISSUE TITLE
Overview slideout

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#5]
On CPT listing pages the text in `the_content` needs to be put into a container that can be toggled. See page 22 of the comps.

**Comment by willthemoor** [comment]
Not sure this is going to be practical. Two reasons:

1. In the comps, the CPT listing/overview pages did not have a right sidebar. Since we've added the right sidebar to all pages in order to facilitate sectional navigation, adding another vertical column for 'Overview' is going to be a mess. 
2. A few of the CPT listing pages have quite a lot of content, including tables. As is, only two will work within the Overview flyout.

We'll either need to come up with an alternative UI or move some content around. An alternative UI might be a full width overview that truncates after the first paragraph or so with a big "Read More" button that reveals the rest of the content, pushing down the CPT listings. Since there are only five CPT landing pages, we might be able to do something more custom for each one.

http://ocs.ecotrust.org/statewide-key-conservation-issues/ :
1. Move almost all of it into separate sub pages, leaving a single paragraph overview. 
2. Attach the Organizations table data to to the KCI data fields model—can be displayed on the overview page and/or the KCI detail page. Bonus: getting rid of the table will be a boon to mobile phones.

http://ocs.ecotrust.org/ecoregions/ is fine as is

http://ocs.ecotrust.org/conservation-opportunity-areas/ or is it http://ocs.ecotrust.org/conservation-opportunity-areas-2/?
1. This one is going to be a map so almost all of this content probably needs to be moved to another page. I don't like the idea of just showing the map without some amount of introduction though. This could also be a candidate for an on page "read more"

http://ocs.ecotrust.org/strategy-habitats/ : 
1. The table could come after the listing. 
2. The table could *be* the listing including (reformatted). 
3. We can include associated ecoregions with each Strategy Habitat in the listing (along with or instead of the summary)

http://ocs.ecotrust.org/ocs-strategy-species/ is fine as is.

**Comment by willthemoor** [comment]
![ocs-overview-slideout](https://cloud.githubusercontent.com/assets/54206/10891714/4dc7abdc-8154-11e5-937e-3bac07c05a75.jpg)

**Comment by ldford** [comment]
Final decision on functionality: For grid and list views, user clicks "Read more" which pushes down list/grid to show all overview content. "Read less" retracts content. Read more includes maximum 1,000 characters with spaces (does that work? could they decide where the cut off in in the WP admin panel?)

Where do we need this?
KCIs - YES to "read more": http://ocs.ecotrust.org/key-conservation-issues/
Ecoregions - leave as is
COAs - leave as is (I worked with Drew on this. ODFW has no more content than what it there)
Strategy Habitats - YES to read more: http://ocs.ecotrust.org/strategy-habitats/
Strategy Species - YES to read more: http://ocs.ecotrust.org/ocs-strategy-species/

**Comment by willthemoor** [comment]
This can be added to the page with the WordPress WYSIYWG's standard MORE button.
