### ISSUE TITLE
Left Sidebar Nav - sticky?

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#58]
Possible to have left sidebar stick to bottom as you are scrolling down a page so that it never completely gets our of sight (similar to WP admin menu). So in screenshot, Oregon Nearshore Strategy would stick to bottom as you continue to scroll down the Strategy Species page. http://ocs.ecotrust.org/ocs-strategy-species/
![image](https://cloud.githubusercontent.com/assets/6453589/11730238/9120bae2-9f48-11e5-8802-1c8a281f5c58.png)

**Comment by dnseminara** [comment]
@ldford I was thinking this over last night and I'm not sure this is practical in the current proposed form.  Nearshore Strategy has its own sub-menu that juts out. Sticking it to the footer won't allow the audience to see the sub-menu. This would also affect Strategy Species sub-menu at shorter browser heights...

**Comment by dnseminara** [comment]
@willthemoor - I think it would take a lot of time/effort to implement this and doesn't seem like an actual need on ODFW's part. Currently sitting with Laura to discuss this. Feel free to close this if you're inclined to agree on the importance of this.

**Comment by willthemoor** [comment]
I think it'd be a pretty sweet feature but I agree that it's pretty far down this list at this point. Time of a 'future' milestone? 

I'm almost finished converting their menu back to a standard WP menu. Just to note here, the classnames we'd want to hook to for this are: `.current-menu-ancestor`,  `.current-menu-parent` and `.current-menu-item` where the first two will be the parent menu item (e.g. "Ecoregions") and the last will be the active page. `.current-menu-ancestor` is the top level of any menu item nested more than one level deep which at this point would only be required for the ONS.
