### ISSUE TITLE
Left Sidebar Nav - highlights

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#59]
Perhaps this is because they are not yet formally a part of the left nav yet, but once you arrive at a piece of structured content (e.g. Acorn Woodpecker, below), the left nav no longer highlights where you are. (in this case it would be "Strategy Species - Birds"). All pages are highlighted correctly within left nav, including the species groups (birds, mammals, etc.). Maybe will be fixed once structured content is added to menu. But should keep in mind for COAs too.

![image](https://cloud.githubusercontent.com/assets/6453589/11730489/585106ca-9f4a-11e5-8e40-23597ee6a4e0.png)

![image](https://cloud.githubusercontent.com/assets/6453589/11730499/60ca3d76-9f4a-11e5-8fbe-23e808f89d04.png)

**Comment by dnseminara** [comment]
I added the logic for the single-species pages, since it's different from the rest (not actually listing the species out)

![screen shot 2015-12-17 at 4 12 46 pm](https://cloud.githubusercontent.com/assets/6739893/11885932/0bf6dc5c-a4d9-11e5-97ed-83428fee6473.png)

**Comment by willthemoor** [comment]
Drew, I'm sorry. I didn't see a notification that you assigned this to yourself! The whole structure of the menu got changed and I'm probably about to wipe this out. 

Looking through other tickets assigned to you now to make sure we don't collide again.

**Comment by dnseminara** [comment]
No worries.

I just used a [switch and jquery](https://github.com/Ecotrust/ocs-wp/commit/84f77bdf2baa9294913ab4fc88c6e74aadbc2c99) to implement the menu stuff for strategy-species. Wasn't that much effort.
