### ISSUE TITLE
Ecoregion map links - Coast Range not working

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#62]
All map links are working on the Ecoregion map EXCEPT Coast Range: http://ocs.ecotrust.org/ecoregions/#

![image](https://cloud.githubusercontent.com/assets/6453589/11824996/8f179986-a331-11e5-9a73-23a1caf4467a.png)

**Comment by dnseminara** [comment]
there is a typo in the svg file. The url is pointing to ecoregion**s** with an 's' in coast-range, rather than ecoregion

**Comment by willthemoor** [comment]
This is fixed.
