### ISSUE TITLE
Change in how search results are displayed

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#69]
In this example, Search bar would say "WOODPECKER" which is what user searched for. The term "Search results" would appear at the top of the search list in smaller type. 
![search-results](https://cloud.githubusercontent.com/assets/6453589/12027723/e57dd4ae-ad7f-11e5-9299-9887bd90a02a.png)

**Comment by dnseminara** [comment]
@ldford - let me know if there's any styling or coloring you want for the "Search results" text. I left it in all caps in the example below, seemed to fit better with the rest of the titles being uppercase as well

![screen shot 2015-12-29 at 10 27 15 am](https://cloud.githubusercontent.com/assets/6739893/12039609/a6a3373c-ae16-11e5-8f14-bf789488067d.png)

**Comment by ldford** [comment]
@dnseminara - Let's give "Search results" the same styling as H2 headers - so it would be a little more subtle than in the example above, but yes, all caps. Here's an H2 header in comparison to the text in the search bar:
![image](https://cloud.githubusercontent.com/assets/6453589/12039756/d9b6e14a-ae17-11e5-83f9-0c5ee1ae7699.png)

**Comment by ldford** [comment]
@willthemoor and @dnseminara - could the two of you connect on who is doing what regarding Search? I know Will was going to work on search functionality and style soon, and I don't want either of you to do unnecessary work.

**Comment by willthemoor** [comment]
I'm going to keep the results part (it will be images where possible) but the Good Mr Drew will take the searchbox/h1 part.

Drew, you can get the search term with `<?php the_search_query(); ?>`
