### ISSUE TITLE
404 and No Search Results Page

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#70]
For both, remove the default yellow box styling.

**If search results:** 
* Searchbox has search term

Copy:
* Headline: No results matched your search terms.
* Make sure all words are spelled correctly
* Simplify your search: try fewer or more general keywords
* Use keywords that reflect words or phrases likely to be in the text of the item you are seeking

**If 404:**
* Searchbox has "Search"

Copy: "Sorry, but the page you were trying to view does not exist." 
* Double check the URL you entered
* Try searching the Oregon Conservation Strategy above
* Return to the homepage (link)

**Comment by ldford** [comment]
are you assigning this to me for sign-off before implementation? Looks good except for use of "URL". Change to "address" - Double check the address you entered (for the 404 page)

Thanks for the 404/search differentiation. i was conflating. Assign to Drew?

**Comment by willthemoor** [comment]
Yes on the sign-off (sorry, forgot to mention!). Yes to Drew.

**Comment by dnseminara** [comment]
@willthemoor - are we supposed to be setting up translations for these two pages or were these just the defaults to begin with? If so, should I be messing with the sage.pot files? If not, can I just use normal html sytanx or should every line of text be enclosed like below?

```
<?php _e('Sorry, but the page you were trying to view does not exist.', 'sage'); ?>
```

**Comment by willthemoor** [comment]
Normal syntax is totally fine.

**Comment by dnseminara** [comment]
@willthemoor this ticket is mostly complete on ocs.ecotrust.org - however it looks like there are now errors present in relation to the highlight_cpt_parent function in extras.php. Unfortunately, I can't replicate them on my dev version. Figured this has something to do with my configurations vs the staging sites ones?

![screen shot 2016-01-06 at 9 55 53 am](https://cloud.githubusercontent.com/assets/6739893/12150020/da45feb2-b45b-11e5-8153-a46c3c137965.png)
