### ISSUE TITLE
Tables and right-hand sidebar collisions

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#71]
I've seen this happen at least 2 places. Right hand "on this page" navigation collides with too-wide table columns. My idea is to suggest to ODFW that the table lives on its own page (where there is no "on this page" navigation and having the table creep into the right-hand navigation is no big deal) and the copy links to that page where users can view the whole table without issue. Thoughts?

http://ocs.ecotrust.org/key-conservation-issue/invasive-species/ (click DOCUMENTED NON-NATIVE INVASIVE FISH AND WILDLIFE SPECIES)

![image](https://cloud.githubusercontent.com/assets/6453589/12043050/bf04dd52-ae35-11e5-9ff3-ea2b3bd95877.png)

**Comment by willthemoor** [comment]
Can you collect any other examples of this into this ticket before we address them? Tables don't like to scale but we can find a solution—I just don't want to over engineer it if it should only be applied to a few.

**Comment by ldford** [comment]
2 additional tables on OCS:
This one I could fix by changing the table header from an H2 to an H3. But it will still flow onto the right-hand sidebar.
http://ocs.ecotrust.org/strategy-habitats/strategy-habitats-summary-by-ecoregion/
![image](https://cloud.githubusercontent.com/assets/6453589/12043867/29f4b99a-ae3e-11e5-89ac-d5acdc8d44e2.png)

This one is more of a problem on Firefox (left) than Chrome (right). Zoom set at 100% for both.
http://ocs.ecotrust.org/ocs-strategy-species/species-data-gaps-research-and-monitoring-needs/
![image](https://cloud.githubusercontent.com/assets/6453589/12043967/1f546070-ae3f-11e5-98fc-c48de7902b6a.png)

ONS:
http://ocs.ecotrust.org/oregon-nearshore-strategy/coastal-communities/
![image](https://cloud.githubusercontent.com/assets/6453589/12044020/bcd02096-ae3f-11e5-90cb-1574616b4c73.png)

http://ocs.ecotrust.org/oregon-nearshore-strategy/factors-stressors-affecting-species-and-habitat/
![image](https://cloud.githubusercontent.com/assets/6453589/12044048/25016274-ae40-11e5-8c06-bf945c1ec6f3.png)

http://ocs.ecotrust.org/oregon-nearshore-strategy/factors-stressors-affecting-species-and-habitat/anthropogenic/

**Comment by ldford** [comment]
Final OCS table with problems the Srank and Ecoregions table here: http://ocs.ecotrust.org/conservation-opportunity-areas/methodology/

Only on FF at 100%.

**Comment by dnseminara** [comment]
I checked in FF and Chrome - using the Tablepress Responsive Plugin. IE may need to be checked...

To update current tablepress tables, they'll simply need to modify the tablepress shortcode, example seen [here](https://tablepress.org/extensions/responsive-tables/)

Options include 'flip', 'scroll', 'collapse'.

They'll need to update/migrate the other tables to Tablepress as well...
