### ISSUE TITLE
Changes to how expandable text looks on grid/list views

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#72]
Relevant pages (see the overview copy at the top): 
http://ocs.ecotrust.org/key-conservation-issues/
http://ocs.ecotrust.org/strategy-habitats/
http://ocs.ecotrust.org/ocs-strategy-species/ 

Example:
![image](https://cloud.githubusercontent.com/assets/6453589/12044167/fae19e94-ae41-11e5-8257-bf426c75dcbb.png)

@dnseminara - Change copy from “Continue reading” to “READ MORE”. Change copy from “Close overview” to “READ LESS”

@dnseminara - Add a horizontal line to visually separate the overview copy from the grid/list view of structured content. So the line would go across the page right underneath the "read more" link. In the design comps, this was a vertical line (below). In our current page set-up, this is obviously a horiz. line.

![image](https://cloud.githubusercontent.com/assets/6453589/12044188/533a3722-ae42-11e5-912c-18d45610c5cb.png)

**Comment by dnseminara** [comment]
@ldford do you want the underneath line to show only on 'READ MORE' or both?

**Comment by ldford** [comment]
both. Thanks.
