### ISSUE TITLE
I can't scroll to ONS! Sometimes.

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#74]
I have only found this in 2 places so far:
http://ocs.ecotrust.org/conservation-toolbox/ (laptop only)
http://ocs.ecotrust.org/strategy-habitats/ (desktop and laptop)

The lefthand menu drop down is long, but the actual page content is relatively short. So I can't see or scroll to ONS in the left-hand nav. Marking this as low priority because it happens so very rarely.

![image](https://cloud.githubusercontent.com/assets/6453589/12044464/aaa7da92-ae46-11e5-961b-bc5d4e2b13a8.png)

**Comment by ldford** [comment]
Perhaps this should be higher priority. On homepage in all 3 browsers, in the left-hand menu, on laptop at 100% zoom, we either can't at all see ONS (FF) or it is cut in half (IE and Chrome). Perhaps it is time to decrease pixel height of the left-hand menu item rectangles (does that make sense?) and take the type size of the main nav copy (Overview, etc.) down a notch or two. This wouldn't solve all problems, but would move us in right direction - at least on homepage.

Also: please note the weird thing happening with the white space in left hand menu in IE (bottom image).

Chrome - ONS in left nav cut off. Can't scroll down to view:
![image](https://cloud.githubusercontent.com/assets/6453589/12054732/b894d832-aeda-11e5-930d-b00d5876805c.png)

FF - ONS in left nav completely absent. Can't scroll.
![image](https://cloud.githubusercontent.com/assets/6453589/12054774/1184e8f6-aedb-11e5-9468-e19acc6eba4c.png)

IE - ONS cut off - but on scroll (discovered I could scroll here), it looks like this with a big white space at left:
![image](https://cloud.githubusercontent.com/assets/6453589/12054792/45dbb9f4-aedb-11e5-9230-36fc20e99cd4.png)

**Comment by willthemoor** [comment]
@ldford Would you give this a shot please. Extra curious about IE.

**Comment by ldford** [comment]
@willthemoor homepages now showing ONS in all cases. IE still has the odd white space (below). ONS also showing now on the Strategy Habitats page and Conservation Toolbox page in all browsers. However, on Conservation Toolbox page, now there is a white space in RIGHT hand sidebar for all browsers (below 2).

IE homepage white space:
![image](https://cloud.githubusercontent.com/assets/6453589/12057014/bdc20c46-aef1-11e5-98e1-a4bea7df85ec.png)

Conservation toolbox page, white space on right, all browsers:
![image](https://cloud.githubusercontent.com/assets/6453589/12057025/cde47064-aef1-11e5-8668-2cc136c645f3.png)
