### ISSUE TITLE
right-hand copy margins too far left

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#76]
@willthemoor We were planning to pull farther to the right. There is too much white space between end of right margin and the "on this page" navigation sidebar. This change would apply to main body copy on pages with right sidebar and also without.

With sidebar:
![image](https://cloud.githubusercontent.com/assets/6453589/12178290/857bfba0-b525-11e5-9aca-3de1c4e1e105.png)

Without (copy would just fill in some of that white space between current right margin and end of green search bar):
![image](https://cloud.githubusercontent.com/assets/6453589/12178335/c41366c8-b525-11e5-9868-6b542ea77cb4.png)

**Comment by willthemoor** [comment]
I struggled with this one some. The line length is currently optimized for legibility. It's based on the mostly commonly recommended per-line character count of 55-65 but I pushed it to 78. Think respecting that limit is important on a site like the OCS where reading huge passages of text is intended. If lines are too long you tend to lose your place when you go to the next line.

We could bump the font size up a bit at wider browser widths so the character counts stay the same (and fill more space) but that will require scaling the headers and I can't fit that in soon.

**Comment by ldford** [comment]
@willthemoor - question: do you have to play with headers every time you change the per line character count? in other words, how easy/difficult is it to play with per line character counts?

Before I make a recommendation on # of characters to increase, I'd like to know how much time it takes each time to change it.

Another (but possibly more timely) option would be to bump up font size and also character counts just a bit. I think that would improve legibility for both IE and Chrome. Thoughts?

**Comment by willthemoor** [comment]
Lines have been lengthened but I kept the font sized the same.
