### ISSUE TITLE
images

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#78]
all images that have captions and/or attributes need to have fig caption
featured images need to be same

**Comment by ldford** [comment]
Photo captions not working inside linkboxes. Link boxes use [linkbox][/linkbox] shortcode. 
See halfway down page in goals and actions section: http://oregonconservationstrategy.org/key-conservation-issue/climate-change/ 

![image](https://cloud.githubusercontent.com/assets/6453589/17415450/c2abcf00-5a3e-11e6-8cab-89c003eabb28.png)

**Comment by dnseminara** [comment]
Awesome - looks good.
