### ISSUE TITLE
Add Success Stories Content Type

### ISSUE THREAD

**Issue by willthemoor** [Ecotrust/ocs-wp#8]
Success stories can be associated with any piece of content on the site. We'll need to:

1. Create a Success Story CPT. Works like a plain post. Default options from current CPTs are a-ok. Does not need extra fields (default post WYSIWYG is is fine).
2. CMB2: Add a success story association repeater field to *all* content types. Can add it as a single CMB field and associate it with all content types at once (including pages) in the 'low' position so it comes up at the end of the editing screens.
3. All templates will need to check for and output them.
4. If possible, let's also create a success story shortcode so that they can be inserted inline within larger content blocks (pages in particular).
5. CSS for success stories is TBD but they should be output with a border and faint background for now.

**Comment by willthemoor** [comment]
Update: this doesn't need to be a CMB2 repeater. Pages will not have more than one Success Story. Bonus because CMB2 has a bug with Rich Text Areas within repeaters at the moment.

**Comment by willthemoor** [comment]
Looking good. I've done a few tweaks and added some super basic CSS. I updated the `post_search_text` plugin (really just a gh repo) to allow for limiting selection to one.

Would be delightful if we could display the title instead of ID but oh well. Found a fork that does that but it's out of date otherwise. I added a little CSS to at least show the ID but it's not wonderful. 

For pages that include a success story:
1. Can you see if there's an incantation that will get it above Revision, Author and Excerpt but below everything else? Alternatively: we can move author and revisions to the right sidebar and get rid of Excerpt entirely.

**Comment by willthemoor** [comment]
Text in the inputs would be nice (instead of IDs—see comment in #33) but this is otherwise in place.  Going to set it to regular priority and beta.

Laura, if you have a 'one day' pile going, let's put this in it! Also, we'll need to loop on CSS eventually. Very basic CSS in place at this point.

**Comment by willthemoor** [comment]
@ldford If you get more time with Sarah, could you add this to the list of *things that could use design attention*?

**Comment by ldford** [comment]
Success story followed by Link box suggested styles. @willthemoor - Feedback?

[OCS_success_style_r1.pdf](https://github.com/Ecotrust/ocs-wp/files/70274/OCS_success_style_r1.pdf)
[OCS_link_box_style_r1.pdf](https://github.com/Ecotrust/ocs-wp/files/70275/OCS_link_box_style_r1.pdf)

**Comment by willthemoor** [comment]
Link box style look great! I'm not understanding what I'm looking at with Success Stories though.

**Comment by ldford** [comment]
Let's go ahead and integrate link box style. I've given Sarah feedback on success stories and she is tweaking and will have something on 12/29.

**Comment by ldford** [comment]
Noticed that if there is a featured image associated with a success story (e.g. http://ocs.ecotrust.org/success-story/millicoma-dace-tiny-but-not-forgotten/ ) it does not actually appear on the page that is associated with said success story (e.g. http://ocs.ecotrust.org/strategy-species/millicoma-dace/). Let me know if that's a bug or user error or if we are just waiting on final styling. Thanks!

**Comment by willthemoor** [comment]
@dnseminara could you look into this one? We don't have an existing style for it but it should be included, probably up top above the headline for now. @ldford can you ask Sarah to include this in her style guide please?

**Comment by ldford** [comment]
Assigning to self as reminder to put up and explain Sarah's style guide for this
