### ISSUE TITLE
Strategy Habitats - Ecoregional Characteristics

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#82]
Ecoregional Characteristics dropdown has no option for "none". Coastal Dunes, Natural Lakes, Aspen Woodlands, Flowing Water, Estuaries all have NO ecoregional characteristics. Currently showing up as error code:
![image](https://cloud.githubusercontent.com/assets/6453589/12212956/7101e468-b625-11e5-871a-c00d74a4d9e0.png)

ODFW would like a dropdown option for "none" in back end, and for user, they would not see "Ecoregional Characteristics" header on the screen at all (preference) - if that is too much work, then just have the header and let it be blank underneath or say "None."

**Comment by ldford** [comment]
Oops forgot to enlarge image. http://ocs.ecotrust.org/strategy-habitat/aspen-woodlands/
![image](https://cloud.githubusercontent.com/assets/6453589/12212972/b4099436-b625-11e5-8819-e22554d533c7.png)

**Comment by willthemoor** [comment]
This is fixed on the display side. There is no option for 'none' but there's a test in the template for the default value without any text. If true, it doesn't output the header (or the error!).
