### ISSUE TITLE
Ecoregions compass map hyperlink

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#83]
Need hyperlink for the compass associated with main ecoregions page http://ocs.ecotrust.org/ecoregions/

**Comment by dnseminara** [comment]
@ldford after the next update - they'll need to copy the following to the opening ```<a>```  tag.

```
<a class="view-map eco-link" href="#">
```

An entire example would look like this
```
<a class="view-map eco-link" href="#">PLACE TEXT YOU WANT CLICKABLE HERE</a>
```
