### ISSUE TITLE
COA grid and list views

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#85]
Grid view: Photos. List alphabetical by COA name

List view: COA ID and Name. Ordered by COA ID number. e.g. COA ID 123, Wallowa Mountains

**Comment by willthemoor** [comment]
The content request for each alternate view is no problem. The re-ordering... requires some extra time/code.

**Comment by willthemoor** [comment]
There was also a request that the grid view for COAs be much smaller so that we could fit 5-6 in a row.
