### ISSUE TITLE
Andrea's error when uploading to Media library

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#92]
Drew - looks like she is using Chrome. I do not receive the same error. Neither does Greg at ODFW. All three of us are administrators. 

Andrea uploads the image, it says it's 100% uploaded, then she gets the "HTTP error" at the top of screen.
![screenshot](https://cloud.githubusercontent.com/assets/6453589/14541130/41f63b24-023d-11e6-875a-47359d35ebef.png)

**Comment by dnseminara** [comment]
@ldford do you know what size of a file she's trying to upload? If she's over the limit, she maybe getting the error as well.

**Comment by ldford** [comment]
She says they are 2MB. I'll ask her to send me one of the files and I'll see if it works for me to find out whether it's an image issue or a user issue. Would that be helpful?

**Comment by ldford** [comment]
Will - need your help. I had Andrea send me her photos, and I can't upload them either. They are both around 2MB. I CAN upload them to Ecotrust.org. I CAN upload small images to OCS. (See: multiple images of Gus and wheelbarrow) So, Drew and I tried a larger image and then got this error (below). Sometimes we are getting a "file too big" error (even though the file is way less than the 8MB limit) and sometimes we are getting this Err_connection_reset error. Drew has tried multiple things. Andrea has a big presentation coming up on April 26 for funders and is hoping to be able to get this working ASAP.

![image](https://cloud.githubusercontent.com/assets/6453589/14547154/c1e2dd52-025f-11e6-84be-8f52f691b99d.png)

**Comment by willthemoor** [comment]
Had to increase the allowed upload size in nginx as well.  Should be all better. I upped the max to 32MB while I was in there because I noticed a few files were already uploaded that were closer to 20MB.
