### ISSUE TITLE
All strategy species parent pages broken and links to child pages broken

### ISSUE THREAD

**Issue by ldford** [Ecotrust/ocs-wp#97]
Amphibians:
http://oregonconservationstrategy.org/ocs-strategy-species/amphibians/ 

![image](https://cloud.githubusercontent.com/assets/6453589/17712230/f2a207d2-63a9-11e6-96eb-cdb540953373.png)

Navigating to salamander from Amphibian, the link looks like this:
http://oregonconservationstrategy.org/ocs-strategy-species/amphibians/%3Cbr%20/%3E%3Cb%3ENotice%3C/b%3E:%20%20Undefined%20variable:%20specID%20in%20%3Cb%3E/var/www/html/app/themes/odfw-ocs-sage/templates/cpt-parts/part-strategy_species.php%3C/b%3E%20on%20line%20%3Cb%3E12%3C/b%3E%3Cbr%20/%3E/strategy-species/cascade-torrent-salamander/

Instead of this:
http://oregonconservationstrategy.org/strategy-species/cascade-torrent-salamander/

**Comment by alisonjbates** [comment]
On it.

**Comment by dnseminara** [comment]
@ldford, I've deployed @alisonjbates fix. Please close if this looks good to go...

**Comment by ldford** [comment]
great!
